CURRENT_GENERATION = 0 # the starting generation
CURRENT_POPULATION = 0 # the starting individual count
MAX_GENERATIONS = 3 # total number of generations
POPULATION = 5 # population size
SELECT = 2 # number of individuals to select from each generation
MIN_FILTER_SIZE = 3 # minimum height and width of convolutional filters
MAX_FILTER_SIZE = 8 # maximum height and width of convolutional filters
MAX_FILTERS = 64 # maximum number of filters in a randomly generated convolutional layer
MIN_FILTERS = 8 # minimum number of filters in a randomly generated convolutional layer
LEARNING_RATE = 0.01
NUM_CLASSES = 10 # number of classes in the dataset
MIN_DENSE_LAYER_SIZE = 256 # minimum number of hidden units in a dense layer
MAX_DENSE_LAYER_SIZE = 1024 # maximum number of hidden units in a dense layer
IMAGE_SHAPE = [32, 32, 3] # H, W, C
MAX_CONVOLUTIONAL_LAYERS = 4 # maximum number of convolutional layers
INITIAL_CONVOLUTIONAL_LAYERS = 3 # number of convolutional layers in the initial population
MAX_DENSE_LAYERS = 3 # maximum number of dense layers
BATCH_SIZE = 512
DIR = 'tournament1' # directory where tournament data will be saved
REMOVE_VALUES = True # boolean indicating if saved values for non-selected models should be deleted
GPUS = 0 # number of GPUs available, if running on CPU set GPUS = 0
