CURRENT_GENERATION = 0
MAX_GENERATIONS = 3
POPULATION = 5
SELECT = 2
MIN_FILTER_SIZE = 3
MAX_FILTER_SIZE = 8
MAX_FILTERS = 32
MIN_FILTERS = 8
LEARNING_RATE = 0.01
NUM_CLASSES = 10
MIN_DENSE_LAYER_SIZE = 64
MAX_DENSE_LAYER_SIZE = 256
IMAGE_SHAPE = [32, 32, 3] # H, W, C
MAX_CONVOLUTIONAL_LAYERS = 4
INITIAL_CONVOLUTIONAL_LAYERS = 3
MAX_DENSE_LAYERS = 3
BATCH_SIZE = 256
DIR = 'tournament1'

# CRAZINESS how much randomness is allowed to happen, reusing convs from earlier layers

# ZOMBIE : bring back models that were mutated away from earier generations